[package]
name = "helix-housekeeper"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
helix-beacon-client.workspace = true
helix-database.workspace = true
helix-datastore.workspace = true
helix-common.workspace = true
helix-utils.workspace = true

# Async and Networking
tokio.workspace = true

# Serialization and Data Format
reth-primitives.workspace = true
serde_json.workspace = true

# Ethereum Types
ethereum-consensus.workspace = true


# Misc
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true

ethers = "2.0.14"
