[package]
name = "helix-website"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
helix-database = {workspace = true}
helix-common = {workspace = true}
helix-utils = {workspace = true}
helix-housekeeper = {workspace = true}
helix-beacon-client = {workspace = true}
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ethereum-consensus = { workspace = true }
askama = "0.12"
alloy-primitives = "0.7.7"
scaler = "1.1.0"
num-format = "0.4.4"
deadpool-postgres = { workspace = true }
async-trait = "0.1.73"
hex = "0.4.3"
url = "2.4.1"
reqwest = "0.11.23"